const { env } = process;

export const ENV = {
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: env.JWT_ACCESS_TOKEN_EXPIRATION_TIME,
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: env.JWT_REFRESH_TOKEN_EXPIRATION_TIME,
  JWT_SECRET: env.JWT_SECRET,
  JWT_ISSUER: env.JWT_ISSUER,
};
